# Generated by Django 3.2 on 2021-04-15 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_app', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('data_check', models.BooleanField(default=False)),
                ('advisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advisors', to='django_app.advisors')),
            ],
            options={
                'db_table': '"data"."data"',
            },
        ),
    ]
