# Generated by Django 3.2 on 2021-04-16 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='advisor',
            new_name='firm',
        ),
    ]
