# Generated by Django 3.2 on 2021-04-15 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=240, verbose_name='Name')),
            ],
            options={
                'db_table': '"django"."role"',
            },
        ),
        migrations.CreateModel(
            name='Advisors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role', to='django_app.roles')),
            ],
            options={
                'db_table': '"django"."advisor"',
            },
        ),
    ]
