# Generated by Django 3.2 on 2021-04-15 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advisors',
            name='user_role',
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
    ]
